<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="8.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StyleForge.Infrastructure\StyleForge.Infrastructure.csproj" />
    <ProjectReference Include="..\StyleForge.Domain\StyleForge.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>c1bdc766-df03-48a0-8743-2a73a5e7dbc8</UserSecretsId>
  </PropertyGroup>

</Project>
